/* eslint-disable */

const composers = {
	ABANDON:          Symbol('abandon'),
	ACCEPT_MODAL:     Symbol('acceptModal'),
	ASSERT:           Symbol('assert'),
	CLICK:            Symbol('click'),
	TAP:              Symbol('tap'),
	CLONE:            Symbol('clone'),
	CONTAIN:          Symbol('contain'),
	DISMISS_MODAL:    Symbol('dismissModal'),
	END_WITH:         Symbol('endWith'),
	EQUAL:            Symbol('equal'),
	EXIST:            Symbol('exist'),
	GO_BACK:          Symbol('goBack'),
	GO_FORWARD:       Symbol('goForward'),
	HAD_NO_ERROR:     Symbol('hadNoError'),
	HAS_EXITED:       Symbol('hasExited'),
	VISIBLE:          Symbol('visible'),
	INTERVAL:         Symbol('interval'),
	LAUNCH_MODE:      Symbol('launchMode'),
	MATCH:            Symbol('match'),
	MATCH_JS:         Symbol('matchJS'),
	MATCH_BRS:        Symbol('matchBRS'),
	MATCH_REPO:       Symbol('matchRepo'),
	MOVE_TO:          Symbol('moveTo'),
	NOT:              Symbol('not'),
	REFRESH:          Symbol('refresh'),
	REPEAT:           Symbol('repeat'),
	SEND_TEXT:        Symbol('sendText'),
	SET_TEXT:         Symbol('setText'),
	SET_SIZE:         Symbol('setSize'),
	START_WITH:       Symbol('startWith'),
	THEN:             Symbol('then'),
	TIMEOUT:          Symbol('timeout'),
	TO_STRING:        Symbol('toString'),
	TO_JSON:          Symbol('toJSON'),
	GETTERS:          Symbol('getters'),
	WAS_MADE:         Symbol('wasMade'),
	WILL_BE_MADE:     Symbol('willBeMade'),
	REQUEST_MATCHES:  Symbol('requestMatches'),
	RESPONSE_MATCHES: Symbol('responseMatches'),
	UNTIL:            Symbol('until'),
	GET_HANDLE:       Symbol('handle'),
	ATTRIBUTES:       Symbol('getAttributes'),
	CSS_PROPS:        Symbol('getCssProp'),
	DEEP_LINK:        Symbol('deepLink'),
	WITH_PROPERTIES:  Symbol('withProperties'),
	IN_REGION:        Symbol('inRegion'),
	LANGUAGE:         Symbol('language'),
	ACCURACY:         Symbol('accuracy'),
	ON_SCREEN:        Symbol('onScreen'),
};

Object.freeze(composers);

module.exports = composers;
