/* eslint-disable key-spacing */

const ENVIROMENT_VARS = {
	SUITEST_SESSION_TOKEN: 'SUITEST_SESSION_TOKEN',
	SUITEST_SESSION_TYPE:  'SUITEST_SESSION_TYPE',
	SUITEST_DEVICE_ID:     'SUITEST_DEVICE_ID',
	SUITEST_APP_CONFIG_ID: 'SUITEST_APP_CONFIG_ID',
	SUITEST_DEBUG_MODE:    'SUITEST_DEBUG_MODE',
	SUITEST_CLOSE_SESSION: 'SUITEST_CLOSE_SESSION',

	SUITEST_CONFIG_DEFAULT_TIMEOUT:         'SUITEST_CONFIG_DEFAULT_TIMEOUT',
	SUITEST_CONFIG_DISALLOW_CRASH_REPORTS:  'SUITEST_CONFIG_DISALLOW_CRASH_REPORTS',
	SUITEST_CONFIG_CONTINUE_ON_FATAL_ERROR: 'SUITEST_CONFIG_CONTINUE_ON_FATAL_ERROR',
	SUITEST_CONFIG_LOG_DIR:                 'SUITEST_CONFIG_LOG_DIR',
	SUITEST_CONFIG_LOG_LEVEL:               'SUITEST_CONFIG_LOG_LEVEL',
	SUITEST_CONFIG_TIMESTAMP:               'SUITEST_CONFIG_TIMESTAMP',

	SUITEST_LAUNCHER_VERSION: 'SUITEST_LAUNCHER_VERSION',

	SUITEST_USER_CONFIG: 'SUITEST_USER_CONFIG',
};

Object.freeze(ENVIROMENT_VARS);

module.exports = ENVIROMENT_VARS;
