const ENVIROMENT_VARS = {
	SUITEST_SESSION_TOKEN: 'SUITEST_SESSION_TOKEN',
	SUITEST_SESSION_TYPE: 'SUITEST_SESSION_TYPE',
	SUITEST_DEVICE_ID: 'SUITEST_DEVICE_ID',
	SUITEST_APP_CONFIG_ID: 'SUITEST_APP_CONFIG_ID',
	SUITEST_LAUNCHER_CHILD_PROCESS: 'SUITEST_LAUNCHER_CHILD_PROCESS',
	SUITEST_LAUNCHER_MAIN_PROCESS: 'SUITEST_LAUNCHER_MAIN_PROCESS',
};

Object.freeze(ENVIROMENT_VARS);

module.exports = ENVIROMENT_VARS;
