const validationKeys = {
	CONFIG_OVERRIDE: Symbol('configOverride'),
	CONFIGURE: Symbol('configure'),
	NON_EMPTY_STRING: Symbol('nonEmptyString'),
	NOT_NEGATIVE_NUMBER: Symbol('notNegativeNumber'),
	ST_VAR_NOT_NEGATIVE_NUMBER: Symbol('stVarOrPositiveNumber'),
	ST_VAR_OR_POSITIVE_NUMBER: Symbol('stVarOrPositiveNumberNotZero'),
	ST_VAR_OR_NUMBER: Symbol('stVarOrNumber'),
	NON_EMPTY_STRING_OR_UNDEFINED: Symbol('nonEmptyStringOrUndefined'),
	STRING_OR_NULL: Symbol('stringOrNull'),
	ARRAY_OF_BUTTONS: Symbol('arrayOfButtons'),
	ELEMENT_PROP_TYPE: Symbol('elementPropType'),
	OPEN_SESSION: Symbol('openSession'),
	UUID: Symbol('uuid'),
	SET_SCREEN_ORIENTATION: Symbol('setScreenOrientation'),
	ELEMENT_SELECTOR: Symbol('elementSelector'),
	ELEMENT_PROPS: Symbol('elementProps'),
	ELEMENT_REPO_PROPS: Symbol('elementRepoProps'),
	REQUEST_MATCHES: Symbol('requestMatches'),
	RESPONSE_MATCHES: Symbol('responseMatches'),
	TEST_LAUNCHER_TEST_COMMAND: Symbol('testLauncherTestCommand'),
	TEST_LAUNCHER_TOKEN: Symbol('testLauncherToken'),
	SESSION_BOOTSTRAP_TOKEN: Symbol('autoBootstrapToken'),
	UNTIL_CONDITION_CHAIN: Symbol('untilConditionChain'),
	STRING: Symbol('string'),
	HAD_NO_ERROR: Symbol('hadNoError'),
	TAKE_SCREENSHOT: Symbol('takeScreenshot'),
	TAP_TYPE: Symbol('tapType'),
	TAP_TYPE_AND_DURATION: Symbol('tapTypeAndDuration'),
	DIRECTIONS: Symbol('direction'),
	LAUNCH_MODE: Symbol('launchMode'),
	CSS_PROPS: Symbol('getCssProperties'),
	ELEMENT_HANDLE: Symbol('handle'),
	ELEMENT_ATTRIBUTES: Symbol('getAttributes'),
	COOKIE_PROPS: Symbol('cookieProps'),
	OCR_COMPARATORS: Symbol('ocrComparators'),
	OCR_OPTIONS: Symbol('ocrOptions'),
	IMAGE_DATA: Symbol('imageData'),
	REGION: Symbol('region'),
	LANGUAGE: Symbol('language'),
	ACCURACY: Symbol('accuracy'),
};

Object.freeze(validationKeys);

module.exports = validationKeys;
