export type ContentMode = {
	SCALE_TO_FILL:     string,
	SCALE_ASPECT_FIT:  string,
	SCALE_ASPECT_FILL: string,
	REDRAW:            string,
	CENTER:            string,
	TOP:               string,
	BOTTOM:            string,
	BOTTOM_LEFT:       string,
	BOTTOM_RIGHT:      string,
	LEFT:              string,
	RIGHT:             string,
	TOP_LEFT:          string,
	TOP_RIGHT:         string,
};
