export type ContentMode = {
	SCALE_TO_FILL:     'scaleToFill',
	SCALE_ASPECT_FIT:  'scaleAspectFit',
	SCALE_ASPECT_FILL: 'scaleAspectFill',
	REDRAW:            'redraw',
	CENTER:            'center',
	TOP:               'top',
	BOTTOM:            'bottom',
	BOTTOM_LEFT:       'bottomLeft',
	BOTTOM_RIGHT:      'bottomRight',
	LEFT:              'left',
	RIGHT:             'right',
	TOP_LEFT:          'topLeft',
	TOP_RIGHT:         'topRight',
};
