/**
 * Elements related constants
 */

// Element properties to check against
export type ElementPropTypes = {
	ALPHA: 'alpha',
	AUTOMATION_ID: 'automationId',
	AUTOMATION_NAME: 'automationName',
	BG_COLOR: 'backgroundColor',
	BORDER_COLOR: 'borderColor',
	BORDER_STYLE: 'borderStyle',
	BORDER_WIDTH: 'borderWidth',
	CLASS: 'class',
	CONTENT_DESCRIPTION: 'contentDescription',
	CONTENT_DESC: 'content-desc',
	FOCUS_MARGIN: 'focusMargin',
	FOCUS_PRIMARY_COLOR: 'focusPrimaryColor',
	FOCUS_PRIMARY_WIDTH: 'focusPrimaryWidth',
	FOCUS_SECONDARY_COLOR: 'focusSecondaryColor',
	FOCUS_SECONDARY_WIDTH: 'focusSecondaryWidth',
	FONT_SIZE: 'fontSize',
	FONT_FAMILY: 'fontFamily',
	FONT_URI: 'fontURI',
	FONT_WEIGHT: 'fontWeight',
	HAS_FOCUS: 'hasFocus',
	HEIGHT: 'height',
	HINT: 'hint',
	HREF: 'href',
	ID: 'id',
	IS_CHECKED: 'isChecked',
	IS_CHECKED_ANDROID_OTTIUM: 'checked',
	IS_CLICKABLE: 'isClickable',
	IS_CLICKABLE_ANDROID_OTTIUM: 'clickable',
	IS_COMPLETELY_DISPLAYED: 'isCompletelyDisplayed',
	IS_ENABLED: 'isEnabled',
	IS_ENABLED_ANDROID_OTTIUM: 'enabled',
	IS_FOCUSABLE: 'isFocusable',
	IS_FOCUSABLE_ANDROID_OTTIUM: 'focusable',
	IS_SELECTED: 'isSelected',
	IS_SELECTED_ANDROID_OTTIUM: 'selected',
	IS_TOUCHABLE: 'isTouchable',
	IMAGE: 'image',
	ITEM_FOCUSED:'itemFocused',
	LEFT: 'left',
	MARGIN:'margin',
	NAME: 'name',
	OPACITY: 'opacity',
	PACKAGE_NAME:'packageName',
	PACKAGE: 'package',
	PADDING: 'padding',
	PIVOT_X: 'pivotX',
	PIVOT_Y: 'pivotY',
	SCALE_X: 'scaleX',
	SCALE_Y: 'scaleY',
	TAG: 'tag',
	TEXT_COLOR: 'color',
	TEXT_CONTENT: 'text',
	TEXT_SIZE: 'textSize',
	TOP: 'top',
	TRANSLATION_X: 'translationX',
	TRANSLATION_Y: 'translationY',
	VALUE: 'value',
	VIDEO_LENGTH: 'videoLength',
	VIDEO_POSITION: 'videoPos',
	VIDEO_STATE: 'videoState',
	VIDEO_URL: 'videoUrl',
	VISIBILITY: 'visibility',
	WIDTH: 'width',
	Z_INDEX: 'zIndex',
	ACCESSIBILITY_IDENTIFIER: 'accessibilityIdentifier',
	BAR_TINT_COLOR: 'barTintColor',
	CONTENT_MODE:'contentMode',
	IMAGE_HASH: 'imageHash',
	FONT_NAME: 'fontName',
	HAS_META_DATA: 'hasMetaData',
	HAS_NAV_MARKERS: 'hasNavMarkers',
	IS_FOCUSED: 'isFocused',
	IS_FOCUSED_ANDROID_OTTIUM: 'focused',
	IS_OPAQUE: 'isOpaque',
	NUMBER_OF_SEGMENTS: 'numberOfSegments',
	PLACEHOLDER: 'placeholder',
	PROPOSAL_URL: 'proposalUrl',
	URL: 'url',
	SELECTED_IMAGE_TINT_COLOR: 'selectedImageTintColor',
	STATE: 'state',
	TEXT_ALIGNMENT: 'textAlignment',
	IMAGE_LOAD_STATE: 'imageLoadState',
	LEFT_ABSOLUTE: 'leftAbsolute',
	TAG_INT: 'tagInt',
	TINT_COLOR: 'tintColor',
	TOP_ABSOLUTE: 'topAbsolute',
	CHILDREN: 'children',
	EXTENDS: 'extends',
	UI_ELEMENT_ID: 'uiElementId',
	INDEX: 'index',
	OFFSET_TOP: 'offsetTop',
	OFFSET_LEFT: 'offsetLeft',
	RESOURCE_ID: 'resource-id',
	IS_LONG_CLICKABLE_ANDROID_OTTIUM: 'long-clickable',
	IS_SCROLLABLE_ANDROID_OTTIUM: 'scrollable',
	BOUNDS: 'bounds',
};

// Needed for keep backward compatibility
export type PropComparators = import('./PropComparators').PropComparators;

// Element special values
export type ValueTypes = {REPO: symbol};
