/**
 * Elements related constants
 */

// Element properties to check against
export type ElementPropTypes = {
	ALPHA:                      symbol,
	AUTOMATION_ID:              symbol,
	AUTOMATION_NAME:            symbol,
	BG_COLOR:                   symbol,
	BORDER_COLOR:               symbol,
	BORDER_STYLE:               symbol,
	BORDER_WIDTH:               symbol,
	CLASS:                      symbol,
	CONTENT_DESCRIPTION:        symbol,
	FOCUS_MARGIN:               symbol,
	FOCUS_PRIMARY_COLOR:        symbol,
	FOCUS_PRIMARY_WIDTH:        symbol,
	FOCUS_SECONDARY_COLOR:      symbol,
	FOCUS_SECONDARY_WIDTH:      symbol,
	FONT_SIZE:                  symbol,
	FONT_FAMILY:                symbol,
	FONT_WEIGHT:                symbol,
	HAS_FOCUS:                  symbol,
	HEIGHT:                     symbol,
	HINT:                       symbol,
	HREF:                       symbol,
	ID:                         symbol,
	IS_CHECKED:                 symbol,
	IS_CLICKABLE:               symbol,
	IS_COMPLETELY_DISPLAYED:    symbol,
	IS_ENABLED:                 symbol,
	IS_FOCUSABLE:               symbol,
	IS_SELECTED:                symbol,
	IS_TOUCHABLE:               symbol,
	IMAGE:                      symbol,
	LEFT:                       symbol,
	MARGIN:                     symbol,
	NAME:                       symbol,
	OPACITY:                    symbol,
	PACKAGE_NAME:               symbol,
	PADDING:                    symbol,
	PIVOT_X:                    symbol,
	PIVOT_Y:                    symbol,
	SCALE_X:                    symbol,
	SCALE_Y:                    symbol,
	TAG:                        symbol,
	TEXT_COLOR:                 symbol,
	TEXT_CONTENT:               symbol,
	TEXT_SIZE:                  symbol,
	TOP:                        symbol,
	TRANSLATION_X:              symbol,
	TRANSLATION_Y:              symbol,
	VIDEO_LENGTH:               symbol,
	VIDEO_POSITION:             symbol,
	VIDEO_STATE:                symbol,
	VIDEO_URL:                  symbol,
	VISIBILITY:                 symbol,
	WIDTH:                      symbol,
	Z_INDEX:                    symbol,
	ACCESSIBILITY_IDENTIFIER:   symbol,
	BAR_TINT_COLOR:             symbol,
	CONTENT_MODE:               symbol,
	IMAGE_HASH:                 symbol,
	FONT_NAME:                  symbol,
	HAS_META_DATA:              symbol,
	HAS_NAV_MARKERS:            symbol,
	IS_FOCUSED:                 symbol,
	IS_OPAQUE:                  symbol,
	NUMBER_OF_SEGMENTS:         symbol,
	PLACEHOLDER:                symbol,
	PROPOSAL_URL:               symbol,
	SELECTED_IMAGE_TINT_COLOR:  symbol,
	STATE:                      symbol,
	TEXT_ALIGNMENT:             symbol,
	LEFT_ABSOLUTE:              symbol,
	TAG_INT:                    symbol,
	TINT_COLOR:                 symbol,
	TOP_ABSOLUTE:               symbol,
};

// Element properties comparators
export type PropComparators = {
	EQUAL:         symbol,
	NOT_EQUAL:     symbol,
	APPROX:        symbol,
	CONTAIN:       symbol,
	NOT_CONTAIN:   symbol,
	GREATER:       symbol,
	EQUAL_GREATER: symbol,
	LESSER:        symbol,
	EQUAL_LESSER:  symbol,
	START:         symbol,
	NOT_START:     symbol,
	END:           symbol,
	NOT_END:       symbol,
};

// Element special values
export type ValueTypes = {REPO: symbol};
