export type Keys = {
	ADD:         '[[Add]]',
	ALT:         '[[Alt]]',
	BACK_SPACE:  '[[Back space]]',
	CANCEL:      '[[Cancel]]',
	CLEAR:       '[[Clear]]',
	COMMAND:     '[[Command]]',
	CONTROL:     '[[Control]]',
	DECIMAL:     '[[Decimal]]',
	DELETE:      '[[Delete]]',
	DIVIDE:      '[[Divide]]',
	DOWN_ARROW:  '[[Down arrow]]',
	END:         '[[End]]',
	ENTER:       '[[Enter]]',
	EQUALS:      '[[Equals]]',
	ESCAPE:      '[[Escape]]',
	F1:          '[[F1]]',
	F2:          '[[F2]]',
	F3:          '[[F3]]',
	F4:          '[[F4]]',
	F5:          '[[F5]]',
	F6:          '[[F6]]',
	F7:          '[[F7]]',
	F8:          '[[F8]]',
	F9:          '[[F9]]',
	F10:         '[[F10]]',
	F11:         '[[F11]]',
	F12:         '[[F12]]',
	HELP:        '[[Help]]',
	HOME:        '[[Home]]',
	INSERT:      '[[Insert]]',
	LEFT_ARROW:  '[[Left arrow]]',
	META:        '[[Meta]]',
	MULTIPLY:    '[[Multiply]]',
	NULL:        '[[NULL]]',
	NUMPAD_0:    '[[Numpad 0]]',
	NUMPAD_1:    '[[Numpad 1]]',
	NUMPAD_2:    '[[Numpad 2]]',
	NUMPAD_3:    '[[Numpad 3]]',
	NUMPAD_4:    '[[Numpad 4]]',
	NUMPAD_5:    '[[Numpad 5]]',
	NUMPAD_6:    '[[Numpad 6]]',
	NUMPAD_7:    '[[Numpad 7]]',
	NUMPAD_8:    '[[Numpad 8]]',
	NUMPAD_9:    '[[Numpad 9]]',
	PAGEDOWN:    '[[Pagedown]]',
	PAGEUP:      '[[Pageup]]',
	PAUSE:       '[[Pause]]',
	RETURN:      '[[Return]]',
	RIGHT_ARROW: '[[Right arrow]]',
	SEMICOLON:   '[[Semicolon]]',
	SEPARATOR:   '[[Separator]]',
	SHIFT:       '[[Shift]]',
	SPACE:       '[[Space]]',
	SUBTRACT:    '[[Subtract]]',
	TAB:         '[[Tab]]',
	UP_ARROW:    '[[Up arrow]]',
	SEARCH:      '[[Search]]',
	DONE:        '[[Done]]',
}
