export type VideoState = {
	STOPPED:            string,
	ERROR:              string,
	PLAYING:            string,
	PAUSED:             string,
	CONNECTING:         string,
	BUFFERING:          string,
	FINISHED:           string,
	IDLE:               string,
	PREPARING:          string,
	PREPARED:           string,
	PLAYBACK_COMPLETED: string,
	UNKNOWN:            string,
	REVERSING:          string,
};
