export type VideoState = {
	STOPPED: symbol,
	ERROR: symbol,
	PLAYING: symbol,
	PAUSED: symbol,
	CONNECTING: symbol,
	BUFFERING: symbol,
	FINISHED: symbol,
	IDLE: symbol,
	PREPARING: symbol,
	PREPARED: symbol,
	PLAYBACK_COMPLETED: symbol,
	UNKNOWN: symbol,
	REVERSING: symbol,
};
